export enum routes {
  HOME = "/",
  AUTH = "/auth",
  MOTOCYCLES = "/motos/",
  SPORTBIKES = "/motos/sport/",
  SPORTBIKE_INFO = "/motos/sport/:id",
  SCOOTER = "/motos/scooter/",
  SCOOTER_INFO = "/motos/scooter/:id",
  MOTOSTUFF = "/motos/parts/",
  MOTOSTUFF_INFO = "/motos/parts/:id",
  ACCESSORIES = "/motos/accessory/",
  ACCESSORIES_INFO = "/motos/accessory/:id",
  HELMETS = "/motos/helmets/",
  HELMET_INFO = "/motos/helmets/:id",
  PROFILE = "/profile",
  EDIT_PROFILE = "/profile/edit",
  MESSAGES = "/profile/messages",
  LIKED_MOTOS = "/profile/liked",
  POST_MOTO = "/post-moto",
  NOT_FOUND = "*",
}