export enum routes {
  HOME = "/",
  AUTH = "/auth",
  ELECTRO_MOTO = "/moto-electro/",
  EMOTO_INFO = "moto-electro/:id",
  MOTOCYCLES = "/moto-all/",
  SPORTBIKES = "/moto-sport/",
  SPORTBIKE_INFO = "/moto-sport/:id",
  SCOOTER = "/moto-scooter/",
  SCOOTER_INFO = "/moto-scooter//id",
  MOTOSTUFF = "/moto-stuff/",
  MOTOSTUFF_INFO = "/moto-stuff/:id",
  ACCESSORIES = "/moto-accessory/",
  ACCESSORIES_INFO = "/moto-accessory/:id",
  HELMETS = "/moto-helmet/",
  HELMET_INFO = "/moto-helmet/:id",
  PROFILE = "/profile",
  EDIT_PROFILE = "/profile/edit",
  MESSSAGES = "/profile/messages",
  LIKED_MOTOS = "/profile/liked-moto",
  POST_MOTO = "/post-moto",
  NOT_FOUND = "*",
}
