export enum routes {
  HOME = "/",
  LOGIN = "/login",
  REGISTER = "/register",
  ELECTRO_MOTO = "/moto-electro/products",
  EMOTO_INFO = "moto-electro/products/:id",
  MOTOCYCLES = "/moto-all/products",
  SPORTBIKES = "/moto-sport/products",
  SPORTBIKE_INFO = "/moto-sport/products/:id",
  SCOOTER = "/moto-scooter/products",
  SCOOTER_INFO = "/moto-scooter/products/id",
  MOTOSTUFF = "/moto-stuff/products",
  MOTOSTUFF_INFO = "/moto-stuff/products/:id",
  ACCESSORIES = "/moto-accessory/products",
  ACCESSORIES_INFO = "/moto-accessory/products/:id",
  HELMETS = "/moto-helmet/products",
  HELMET_INFO = "/moto-helmet/products/:id",
  PROFILE = "/profile",
  EDIT_PROFILE = "/profile/edit",
  MESSSAGES = "/profile/messages",
  LIKED_PRODUCTS = "/profile/liked-products",
  POST_PRODUCT = "/post-product",
}
